services:
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    ports:
      - "3000:80"
  backend:
    build: ./backend
    environment:
      - PORT=5000
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=restaurants
    ports:
      - "5000:5000"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
